### ISSUE TITLE
Can't install npm package firebase version 4.13.1

### ISSUE THREAD

**Issue by jscruggs** [jacekschae/learn-reagent-course-files#16]
In episode 20 https://www.jacekschae.com/courses/learn-reagent-pro/21653-javascript-interop/57060-20-firebase-setup at about 2:22 the video asks the viewer to install firebase version 4.13.1 however, when I try, I get this error:
~~~~
$ npm install --save firebase@4.13.1
npm WARN deprecated core-js@2.5.5: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> grpc@1.10.1 install /home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.18.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.18.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file 
make: Entering directory '/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
make: Entering directory '/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
make: *** [grpc.target.mk:396: Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
make: Leaving directory '/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-7625-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.3.0-7625-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc
node-pre-gyp ERR! node -v v10.18.1
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.oexec install script
In file included from ../deps/grpc/src/core/lib/backoff/backoff.h:22,
                 from ../deps/grpc/src/core/lib/backoff/backoff.cc:19:
../deps/grpc/src/core/lib/iomgr/exec_ctx.h:22:10: fatal error: grpc/support/atm.h: No such file or directory
   22 | #include <grpc/support/atm.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [grpc.target.mk:396: Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
make: Leaving directory '/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-7625-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/jakescruggs/projects/learn-reagent-course-files/giggin/node_modules/grpc
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
~~~~

**Comment by jacekschae** [comment]
Hi @jscruggs,

Sorry seeing that you have problems here. I assume that despite this problem the app doesn't work and you are not able to follow?

I know that firebase changed imports from version 5 and this is why I locked in on 4.13 while recording.

```clj
(ns fb.init
  (:require ["firebase/app" :as firebase]))
```
 you might try this instead\

```clj
["@firebase/app" :default (firebase)]
["@firebase/firestore"]
```
Note that it is no longer `:as` firebase but rather `:default` or `:refer (firebase)`.

I'm currently traveling and won't be back before mid Feb therefore please forgive me on not being able to address this in more detail now.

I'll re-record the videos including firebase when I'm back to include the latest version of firebase.

**Comment by jacekschae** [comment]
@jscruggs could we close this one?

**Comment by jscruggs** [comment]
Of course, close it. Thanks for the advice. Love the course and I hope to get back to it when life lets me.

**Comment by ninamma** [comment]
> I'll re-record the videos including firebase when I'm back to include the latest version of firebase.

Hi @jacekschae, I'm hitting a similar error to OP when installing (with both npm and yarn) firebase version 4.13.1.

I see that you've updated the firebase lessons with new code under "Learning in 2022" - should we also be using the latest version of the firebase package now?

**Comment by jacekschae** [comment]
Hi there, try with the latests version -- it should work.
